"""update RoomBookingModel to show unit price

Revision ID: 02a95d364e4d
Revises: 617a0311b3e5
Create Date: 2026-08-12 11:46:14.642219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a95d364e4d'
down_revision = '617a0311b3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
