"""edit reviewmodel

Revision ID: 1eac5d1ec3c1
Revises: d0acd028ec67
Create Date: 2026-08-13 12:00:42.665261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eac5d1ec3c1'
down_revision = 'd0acd028ec67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('booking_ref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_ref', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
