"""add discounts model

Revision ID: 3dfefd6e17b9
Revises: 86df482e151f
Create Date: 2026-08-11 16:20:36.105277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfefd6e17b9'
down_revision = '86df482e151f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('percentage_off', sa.Float(), nullable=False),
    sa.Column('booking_start_date', sa.Date(), nullable=True),
    sa.Column('booking_end_date', sa.Date(), nullable=True),
    sa.Column('stay_start_date', sa.Date(), nullable=True),
    sa.Column('stay_end_date', sa.Date(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_discounts_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_discounts_room_id_rooms')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
