"""update room booking table

Revision ID: 617a0311b3e5
Revises: 8bd3505687d1
Create Date: 2026-08-12 10:17:43.840358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617a0311b3e5'
down_revision = '8bd3505687d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_rates', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
