"""create lead time table

Revision ID: 62ec7e71e6fa
Revises: 3dfefd6e17b9
Create Date: 2026-08-12 08:13:49.914820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ec7e71e6fa'
down_revision = '3dfefd6e17b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_time_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_lead_time_rules_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_lead_time_rules_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_time_rules')
    # ### end Alembic commands ###
