"""new test

Revision ID: f7b0c6376ae2
Revises: 
Create Date: 2026-08-21 15:54:08.038194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b0c6376ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('date_of_deposit_charge', sa.Date(), nullable=False),
    sa.Column('date_of_remainder_charge', sa.Date(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_bookings_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref')
    )
    op.create_table('events',
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('no_of_tickets', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_events_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('no_of_rooms', sa.Integer(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_rooms_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('percentage_off', sa.Float(), nullable=False),
    sa.Column('booking_start_date', sa.Date(), nullable=True),
    sa.Column('booking_end_date', sa.Date(), nullable=True),
    sa.Column('stay_start_date', sa.Date(), nullable=True),
    sa.Column('stay_end_date', sa.Date(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_discounts_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_discounts_room_id_rooms')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('event_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('no_of_people', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_bookings_event_id_events')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref')
    )
    op.create_table('lead_time_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_lead_time_rules_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_lead_time_rules_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('review', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_reviews_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('room_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price_locked', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_room_bookings_booking_id_bookings')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_holds_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('modifier_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_rates_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_rates')
    op.drop_table('room_holds')
    op.drop_table('room_bookings')
    op.drop_table('reviews')
    op.drop_table('lead_time_rules')
    op.drop_table('event_bookings')
    op.drop_table('discounts')
    op.drop_table('rooms')
    op.drop_table('events')
    op.drop_table('bookings')
    op.drop_table('sites')
    op.drop_table('hotels')
    # ### end Alembic commands ###
